### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by ghost** [joshstar/AniList-Discord-Bot#12]
```
>npm start

> anilist-discord-bot@1.0.0 start C:\Users\Utilizador\Desktop\discord-search-bot
> node src/index.js

(node:2052) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\Utilizador\Desktop\discord-search-bot\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:309:26)
    at WebSocketConnection.emit (events.js:219:5)
    at WebSocketConnection.onClose (C:\Users\Utilizador\Desktop\discord-search-bot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\Utilizador\Desktop\discord-search-bot\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:219:5)
    at WebSocket.emitClose (C:\Users\Utilizador\Desktop\discord-search-bot\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\Utilizador\Desktop\discord-search-bot\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:224:7)
    at net.js:666:12
(node:2052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by alex-star-gh** [comment]
Read `Error: Incorrect login details were provided.`
Make sure to correctly follow the steps in the [Getting started section](https://github.com/AniList/discord-search-bot#getting-started) of the readme and use the correct token type.
